# Generated by Django 5.0.6 on 2024-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='locker_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.AddField(
            model_name='student',
            name='enter_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
