# Generated by Django 5.0.6 on 2024-07-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_student_number_student_locker_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enter_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='exit_time',
            field=models.DateTimeField(),
        ),
    ]
