# Generated by Django 5.0.6 on 2024-07-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_enter_time_alter_student_exit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='field_of_study',
        ),
    ]
