# Generated by Django 5.0.6 on 2024-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.CharField(default=35, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='enter_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='exit_time',
            field=models.DateTimeField(),
        ),
    ]
